import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    title: {
      flex: 1,
      textTransform: "uppercase",
      fontSize: 24,
      textAlign: "center",
      color: "#544E4D",
      fontWeight: "bold",
      marginTop: 20,
      //borderWidth: 1,
    },
    notTitle: {
      flex: 10,
      fontSize: 24,
      textAlign: "center",
      color: "rgba(0, 70, 150,0.9)",
      fontWeight: "bold",
      marginTop: 20,
      //borderWidth: 1,
    },
    notNotTitle: {
      flex: 2,
      fontSize: 24,
      textAlign: "center",
      color: "rgba(0, 70, 150,0.9)",
      fontWeight: "bold",
      marginTop: 20,
      //borderWidth: 1,
      alignContent: "flex-end",
      flexDirection: "column-reverse",
    },
    choices: {
      flexDirection: "row",
    },
    choiceButton: {
      flex: 1,
      padding: 5,
      margin: 5,
      marginRight: 5,
      borderWidth: 2,
      backgroundColor: "white",
      borderColor: "grey",
      borderRadius: 5,
    },
    choiceText: {
      fontSize: 14,
      textAlign: "center",
      color: "#544E4D",
      fontWeight: "bold",
    },
    gifcontent: {
      flexDirection: "column",
      justifyContent: "center",
      backgroundColor: "white",
      borderWidth: 2,
      backgroundColor: "white",
      borderColor: "grey",
      paddingTop: 10,
      borderRadius: 10,
      //Sombreado
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 12,
      },
      shadowOpacity: 0.58,
      shadowRadius: 16.0,
  
      elevation: 24,
    },
    result: {
      margin: 20,
      alignItems: "center",
    },
    resultText: {
      fontSize: 36,
    },
    text: {
      fontSize: 18,
    },
    fondoStyle: {
      flex: 1,
      resizeMode: "contain",
      width: "100%",
      height: "100%",
    },
    blurContainer: {
      flex: 1,
      backgroundColor: "rgba(30, 30, 30, 0.1)",
    },
    blur: {
      flex: 1,
      backgroundColor: "transparent",
      padding: 20,
    },
    image: {
      width: 150,
      height: 150,
      resizeMode: "contain",
      alignSelf: "center",
      marginBottom: 20,
      justifyContent: "center",
      transform: [{ scaleX: -1 }],
    },
    image2: {
      width: 150,
      height: 150,
      resizeMode: "contain",
      alignSelf: "center",
      marginBottom: 20,
      justifyContent: "center",
    },
    resultadoImgContainer: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
    },
    resultadoImgHijo: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      resizeMode: "contain",
      alignSelf: "center",
      justifyContent: "center",
    },
    resultadoImgHijo2: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
  });